---
# Stand up a home automation host
- name: Configure home assistant
  hosts: all
  remote_user: ubuntu

  tasks:
    # Set proper hostname & reboot
    - name: Set hostname
      ansible.builtin.hostname:
        name: homeautomation
      become: yes
    - name: Reboot system
      ansible.builtin.reboot:
        msg: "Baseline ansible setup complete, rebooting!"
      become: yes
    # Install & enable container runtime
    - name: Ensure podman-docker is installed
      ansible.builtin.apt:
        name: podman-docker
        state: present
      become: yes
    - name: Ensure podman socket is available
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
      become: yes
    # Stand up HomeBridge
    - name: Copy docker-compose.yaml to remote host
      ansible.builtin.copy:
        src: ../../docker/homebridge/docker-compose.yaml
        dest: /home/ubuntu/homebridge-docker-compose/docker-compose.yaml
    - name: Stand up homebridge via docker-compose
      community.docker.docker_compose:
        project_src: /home/ubuntu/homebridge-docker-compose
        state: present
