---
# Handles baseline maintenance and hardening settings.
- name: Configure unattended upgrades
  hosts: all
  remote_user: ubuntu

  tasks:
    # Package unattended-upgrades should already be installed via cloud-init
    - name: echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | sudo debconf-set-selections  - auto install security updates
      debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'
    #- name: apt install unattended-upgrades
    #  apt: name=unattended-upgrades
    - name: dpkg-reconfigure -f noninteractive unattended-upgrades
      command:
        cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
        creates: /etc/apt/apt.conf.d/20auto-upgrades
